steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js # <--- 这一步被修改了！
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Node.js 版本保持不变
          npm-version: '8'   # <--- 新增的行！强制使用 npm v8

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run npm run build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
